- name: Include ACME client management tasks
  include_tasks: manage_client.yml

- name: Include directory management tasks
  include_tasks: manage_dirs.yml
  when: cert_manager_account != 'create'

- name: Include ACME account management tasks
  include_tasks: manage_account.yml
  when: cert_manager_account != 'create'

- name: Include certificate management tasks
  include_tasks: manage_certs.yml
  when: cert_manager_account != 'create'

- name: Include ACME account creation tasks
  include_tasks: create_account.yml
  when: cert_manager_account == 'create'
