- name: Retrieve {{ cert_manager_cert_main_domain }} conf file information
  stat:
    path: "{{ cert_manager_client_dir }}/{{ cert_manager_cert_main_domain }}/{{ cert_manager_cert_main_domain }}.conf"
  become: true
  register: cert_manager_conf_file_stat_result

- name: Revoke {{ cert_manager_cert_main_domain }} certificate
  command:
    cmd: >
      sudo -u {{ cert_manager_user|quote }}
      {{ cert_manager_client_dir|quote }}/acme.sh
      --revoke --domain {{ cert_manager_cert_main_domain|quote }}
    warn: false
  become: true
  when:
    - cert_manager_revoke|default(false)
    - cert_manager_conf_file_stat_result.stat.exists

- name: Remove {{ cert_manager_cert_main_domain }} certificate
  command:
    cmd: >
      sudo -u {{ cert_manager_user|quote }}
      {{ cert_manager_client_dir|quote }}/acme.sh
      --remove --domain {{ cert_manager_cert_main_domain|quote }}
    warn: false
  become: true
  when: cert_manager_conf_file_stat_result.stat.exists
