- name: Verify all hosts
  hosts: all
  vars_files:
    - ../../vars/main.yml
  tasks:
    - name: Retrieve state of ACME client
      command:
        cmd: >
          sudo -u {{ cert_manager_user|quote }}
          {{ cert_manager_client_dir|quote }}/acme.sh
          --version
        warn: false
      register: client_version_result

    - name: Run tests
      assert:
        that:
          - client_version_result.stdout is search('v' + cert_manager_client_version|regex_escape)
